version: '1.0.{build}'
configuration:
- Debug
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore "src\Bristlecone\Bristlecone.fsproj" -v Minimal
- appveyor-retry dotnet restore "tests\Bristlecone.Tests\Bristlecone.Tests.fsproj" -v Minimal
build_script:
- dotnet build "src\Bristlecone\Bristlecone.fsproj" -c %CONFIGURATION% --version-suffix %LABEL%
test_script:
- dotnet test "tests\Bristlecone.Tests\Bristlecone.Tests.fsproj" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'