// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Bristlecone")>]
[<assembly: AssemblyCompanyAttribute("")>]
[<assembly: AssemblyProductAttribute("Bristlecone")>]
[<assembly: AssemblyDescriptionAttribute("Time-series modelling in F#")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

