// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Bristlecone")>]
[<assembly: AssemblyCompanyAttribute("University of Oxford; University of Cambridge")>]
[<assembly: AssemblyProductAttribute("Bristlecone")>]
[<assembly: AssemblyDescriptionAttribute("Time-series modelling in F#")>]
[<assembly: AssemblyVersionAttribute("3.1.0")>]
[<assembly: AssemblyFileVersionAttribute("3.1.0")>]
do ()

