#r "../../packages/NETStandard.Library.NETFramework/build/net461/lib/netstandard.dll"
#r "../../packages/FSharp.Data/lib/net45/FSharp.Data.dll"
#r "../../packages/MathNet.Numerics/lib/netstandard2.0/MathNet.Numerics.dll"
#r "../../packages/MathNet.Numerics.FSharp/lib/netstandard2.0/MathNet.Numerics.FSharp.dll"
#r "bin/Debug/netstandard2.0/Microsoft.Research.Oslo.dll"
#r "bin/Debug/netstandard2.0/Bristlecone.dll"