// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("Bristlecone.Dendro")>]
[<assembly: AssemblyProductAttribute("Bristlecone")>]
[<assembly: AssemblyDescriptionAttribute("Time-series modelling in F#")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "Bristlecone.Dendro"

    [<Literal>]
    let AssemblyProduct = "Bristlecone"

    [<Literal>]
    let AssemblyDescription = "Time-series modelling in F#"

    [<Literal>]
    let AssemblyVersion = "1.0.0"

    [<Literal>]
    let AssemblyFileVersion = "1.0.0"

    [<Literal>]
    let AssemblyConfiguration = "Release"
